### ISSUE TITLE
Support for Bootstrap 4?

### ISSUE THREAD

**Issue by detj** [StevenIseki/bootstrap-css#3]
Since Bootstrap 4 is almost ready, is there any plan to support the latest Bootstrap? Bootstrap 4.x.x uses SCSS whereas 3.x.x uses less. How much effort do you think porting would take?

**Comment by svnm** [comment]
Yes, I am planning to support Bootstrap 4. I don't imagine it will take too much effort to port it over.
I will leave this issue, and might setup a branch for bootstrap-4. Any help will be appreciated.

**Comment by terencechow** [comment]
@StevenIseki looking at bootstrap 4 it uses scss. I don't mind helping out but am a bit confused on steps since bootstrap 4 doesn't have less components. Should this project switch to scss?

**Comment by svnm** [comment]
Yes it should

**Comment by terencechow** [comment]
I forked this and made some changes to allow bootstrap4 but don't have any access to your repo to add branches etc.
https://github.com/terencechow/bootstrap-css

**Comment by svnm** [comment]
Hi @terencechow thanks for your help on this project. I am looking for some help maintaining it, and would appreciate some users who I would add as collaborators to the keep the version up to date, until this build step can be added to the official twitter bootstrap repo.

If you have set this up using scss and version 4 that is great, you can create a pull request just by clicking the new pull request button on your repo. However I don't see any commits in your branch at the moment, have you not pushed them from you local. Try `git push origin master` If all is good I can accept your pr and use it as a base to set up v4. 

Either way I was looking to set this up myself tomorrow or the next day. So if you can get the pr in I will use it as a base, otherwise I will push ahead, and would love support from you and some others in maintaining 

So the plan is for v4 support to come this week.

**Comment by svnm** [comment]
Thanks for you great work @terencechow I have merged your pr and added you as a collaborator. So now you can work directly on this repo. Just `git clone` this one now. I will give this a test and we should be good to publish it tonight.

**Comment by svnm** [comment]
Again thanks @terencechow for getting this up and running.

Unfortunately we had a small bug in importing 1 file. Which I published, I did test before publishing but then forgot to make the fix.

So in short we have `4.0.0-alpha.5` ... but it actually imports bootstrap `4.0.0-alpha.6`. Beta is coming out very soon then we can publish that and forget that I made this mistake... sorry.
